### ISSUE TITLE
csv export: german special characters not handled correctly ("ß")

### ISSUE THREAD

**Issue by SoraMakes** [Glutamat42/cashbook-api#1]
contains illegal character at /var/www/html/app/Services/ExportService.php:245)
[stacktrace]
#0 /var/www/html/app/Services/ExportService.php(245): PharData->addFile('/var/www/html/s...', 'documents/50_Se...')
#1 /var/www/html/app/Services/ExportService.php(146): App\\Services\\ExportService->addDocumentsToArchive(Object(PharData))
#2 /var/www/html/app/Services/ExportService.php(77): App\\Services\\ExportService->createTarGz('/var/www/html/s...', '/var/www/html/s...', true)
#3 /var/www/html/app/Console/Commands/ExportDataCommand.php(30): App\\Services\\ExportService->exportData(true, true, 'tar.gz')
#4 /var/www/html/vendor/illuminate/container/BoundMethod.php(36): App\\Console\\Commands\\ExportDataCommand->handle()
#5 /var/www/html/vendor/illuminate/container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /var/www/html/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#7 /var/www/html/vendor/illuminate/container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Laravel\\Lumen\\Application), Array, Object(Closure))
#8 /var/www/html/vendor/illuminate/container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Laravel\\Lumen\\Application), Array, Array, NULL)
#9 /var/www/html/vendor/illuminate/console/Command.php(211): Illuminate\\Container\\Container->call(Array)
#10 /var/www/html/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#11 /var/www/html/vendor/illuminate/console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#12 /var/www/html/vendor/symfony/console/Application.php(1078): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /var/www/html/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\ExportDataCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/www/html/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/www/html/vendor/laravel/lumen-framework/src/Console/Kernel.php(160): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 /var/www/html/artisan(35): Laravel\\Lumen\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#17 {main}
"}

**Comment by SoraMakes** [comment]
fixed
